### ISSUE TITLE
Add a few primary templates

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#10]
bring them over as is, then improve.

Will break into design and front end tickets once this is done for iterative improvements.

**Comment by gnakm** [comment]
- Incorporate new line length

**Comment by gnakm** [comment]
![templates](https://cloud.githubusercontent.com/assets/13420618/13338143/791d6116-dbed-11e5-8b98-78c2a8352117.png)

@emilyville I edited the existing templates that we have on the playbook. Do we need anything else?
@webinista I will send you the sketch file of these with text for each one!

**Comment by emilyville** [comment]
Awesome! I am thinking these will just be images in the style guide, and
when we do have the downloadable rr-rails sample app ready, they will be
built into there.

**Comment by gnakm** [comment]
This is currently on the beta.
