### ISSUE TITLE
Templates > Content Templates

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#103]
<img width="507" alt="screen shot 2016-03-03 at 9 14 39 am" src="https://cloud.githubusercontent.com/assets/13420618/13502583/66baaae6-e120-11e5-9276-2344a65f45bd.png">

The content description does not have to have a box around it. I just put it there to block off area. 

![topic landing](https://cloud.githubusercontent.com/assets/13420618/13502270/1db14e1e-e11f-11e5-8f03-81c2e7e388b5.png)

[Topic landing](https://www.vets.gov/disability-benefits/) pages introduce main site areas. The template includes a brief introduction and card navigation linking to secondary content. It may also include quick links and help or contact information specific to the topic.

![detailed landing](https://cloud.githubusercontent.com/assets/13420618/13502297/3e716f12-e11f-11e5-9d2c-d4946efa3582.png)

[Detailed landing](https://www.vets.gov/disability-benefits/conditions/) pages communicate an overview of secondary information with links to faceted content. The template utilizes list style navigation and may include callout boxes, quick links and help or contact information specific to the topic.

![panel filter](https://cloud.githubusercontent.com/assets/13420618/13502326/62a6fee2-e11f-11e5-9f80-3481d9d3bfdb.png)

[Panel filter](https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/) pages help visitors quickly identify content paths that are relevant to their specific circumstances. The template includes definition blocks that function as a filtering mechanism.

![action page](https://cloud.githubusercontent.com/assets/13420618/13502344/73a85704-e11f-11e5-8430-415e542d70fc.png)

[Action pages](https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/c-123/) provide in-depth detail on particular topics and should help visitors to feel confident in taking next steps or accessing calls-to-action as needed. The template may also include definition blocks, Callout boxes and help or contact information specific to the topic.

![information page](https://cloud.githubusercontent.com/assets/13420618/13502367/8df176e0-e11f-11e5-928f-8dabed630886.png)

[Information pages](https://www.vets.gov/disability-benefits/conditions/service-connected/) include an introduction and supporting body copy.

![process page](https://cloud.githubusercontent.com/assets/13420618/13502388/a0eb6daa-e11f-11e5-89a7-6c49eee0980d.png)

[Process pages ](https://www.vets.gov/disability-benefits/apply-for-benefits/)support visitors through complex workflows and set them up for successful engagement with VA process. The template utilizes a process list and may also include list form navigation.

**Comment by webinista** [comment]
@gnakm I am sure this sounds like a weird question, but are these templates just supposed to be image templates?

**Comment by emilyville** [comment]
Not Gina, but chiming in anyway!!

I think that'd be fine, kinda like this: 
https://www.vets.gov/playbook/design/templates/

Eventually we should have these built out in the sample app and we can link to them, or something.

**Comment by webinista** [comment]
Oh. I didn't know there was a Vets.gov Playbook!
