### ISSUE TITLE
Branding > Color

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#107]
<img width="631" alt="screen shot 2016-03-03 at 12 36 56 pm" src="https://cloud.githubusercontent.com/assets/13420618/13508696/eb01adb0-e13c-11e5-8fc1-d68d83ae3558.png">
<img width="633" alt="screen shot 2016-03-03 at 12 37 06 pm" src="https://cloud.githubusercontent.com/assets/13420618/13508700/eca7f9e4-e13c-11e5-82f5-9c998169d921.png">

Color:
This palette is designed to support a range of distinct visual styles that continue to feel connected. The intent of the palette is to convey a warm and open American spirit, with bright saturated tints of blue, grounded in sophisticated deeper shades of cool blues and grays. These colors — combined with clear hierarchy, good information design, and ample white space — should leave users feeling welcomed and in good hands.

This is a simple, minimalist color palette. Shades of blue dominate, providing a neutral backdrop on which brighter shades, clean type treatment, and bright white content areas "pop" on the page.

Primary: 
This palette’s primary colors are blue, gray, and white. Blue is commonly associated with trust, confidence, and sincerity; it is also used to represent calmness and responsibility.

Primary
Hex: #0071bc

Primary- darker
Hex: #205493

Primary- darker
Hex: #205493

Gray Dark
Hex: #205493

Gray Lightest
Hex: #205493

White
Hex: #FFFFFF

Secondary:
These are accent colors to provide additional lightness and style to pages looking for a more modern flair. These colors should be used to highlight important features on a page, such as buttons and breadcrumb. They should be used sparingly and never draw the eye to more than one piece of information at a time.

Gold
Hex: #FAC922

Green
Hex: #2e8540

Tertiary: 
These colors are used primarily for content-specific needs, such as alerts and callout information. They should never overpower the primary colors.

Primary-alt-lightest
Hex: #e1f3f8

green-lightest
Hex: #e7f4e4

secondary-lightest
Hex: #f9dede

**Comment by webinista** [comment]
Blocks #118
