### ISSUE TITLE
Design - identify component buckets

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#11]
Which areas of design will we need to cover - design components, templates, branding, font usage, etc. 

Can likely stay consistent with US WDS but I imagine we can be more specific in some cases.

**Comment by gnakm** [comment]
I was thinking:

**Typography**
- Typeface
- Sizing
- Pairing and Styles

**Design Components**
- Header/Footer
- Navigation
- Links
- Buttons

**Color**
- Palette
- Combination
- Alerts

**Templates**

**Branding**

I think it'd be nice to add forms but I don't know if it should get it's own section or go under design components

**Comment by emilyville** [comment]
It's here:
https://github.com/department-of-veterans-affairs/roadrunner/blob/gh-pages/docs/StyleGuide.md

and awesome. Go @gnakm - and closing.
