### ISSUE TITLE
Decide and Communicate Browser Support

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#116]
Add a page or some words to this effect on roadrunner, explaining our browser support

https://www.healthcare.gov/browser-compatibility/

**Comment by emilyville** [comment]
from @staceylanger Proposal

For Vets.gov, we need unsupported browser functionality (e.g., banner) that accomplishes the following:
1. Encourages users to upgrade. 
2. Gives them access to another channel (e.g., phone or physical location). For example, have some sort of "Unable to upgrade?" entry point that directs them to a 1-800 number or the facility locator. 
3. Ensure pretty robust backwards compatibility with old browsers in the facility locator only. 
This accomplishes everything we've talked about:
1. Minimizes resources spent on testing and working through bugs in old browsers, while
2. Ensuring every veteran can get help.

**Comment by webinista** [comment]
So is IE8 our minimum, and is that also true for the Jekyll portion of the site?

**Comment by emilyville** [comment]
Closing, this has been addressed in vets-website
