### ISSUE TITLE
Branding > Typography Section

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#119]
<img width="434" alt="screen shot 2016-03-04 at 3 07 48 pm" src="https://cloud.githubusercontent.com/assets/13420618/13542896/2eef8162-e21b-11e5-9669-12c80ee9136f.png">

Text
Source Sans Pro:
Source Sans Pro is an open-source sans serif typeface created for legibility in UI design. With a variety of weights that read easily at all sizes, Source Sans Pro provides clear headers as well as highly-readable body text. 
Inspired by twentieth-century American gothic typeface design, its slender but open letters offer a clean and friendly simplicity. Advanced hinting allows Source Sans Pro to render well on Windows systems which run Cleartype, and across browsers and devices. Moreover, it supports a variety of languages and alphabets, including Western and European language, Vietnamese, pinyin Romanization of Chinese, and Navajo.

**Source**: US Web Design Standards [https://playbook.cio.gov/designstandards/visual-style/#typography]

Roboto Slab

Roboto Slab is an open-source slab serif typeface based on Roboto. With only four variations of weight, Roboto Slab is appropriate for headers and can be paired with other san serifs. Roboto Slab is used in the breadcrumb and title headers throughout Vets.gov to convey a friendly and welcoming gesture to users.

**Comment by webinista** [comment]
Blocks #118
