### ISSUE TITLE
Branding > Typesetting, Alignment, Line Length

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#120]
<img width="433" alt="screen shot 2016-03-04 at 3 08 01 pm" src="https://cloud.githubusercontent.com/assets/13420618/13542921/6ec88ca2-e21b-11e5-84a3-47fe474a198c.png">
<img width="431" alt="screen shot 2016-03-04 at 3 08 14 pm" src="https://cloud.githubusercontent.com/assets/13420618/13542930/7ae27f5c-e21b-11e5-8d95-5d1108b54dd3.png">
<img width="433" alt="screen shot 2016-03-04 at 3 08 26 pm" src="https://cloud.githubusercontent.com/assets/13420618/13542937/84b6f1ca-e21b-11e5-8808-884bc1078729.png">

**Typesetting**: Readable text allows users to efficiently read and take in textual information, whereas text that is not readable turns off readers or makes it challenging for them to stay focused. The following guidelines promote good readability.

**Alignment**: Type set flush left provides the eye a constant starting point for each line, making text easier 
to read.

**Line Length**: Controlling the length of lines of text in extended copy makes reading more comfortable by helping readers’ eyes flow easily from one line to the next. Somewhere between 50 and 75 characters per line is broadly considered to be a readable line length, while 66 characters is considered the ideal. Other factors beyond line length also affect reading comfort. Text with more space between lines can have somewhat longer line length. Also, contexts in which users will not be reading long passages of text (such as footnotes or alerts) can safely be set with somewhat longer lines as well.

No codes for these sections
More reference: https://playbook.cio.gov/designstandards/visual-style/#typefaces

**Comment by webinista** [comment]
Blocks #118

**Comment by webinista** [comment]
@gnakm Should I copy and paste the examples from the [playbook](https://playbook.cio.gov/designstandards/visual-style/#typefaces)?

**Comment by gnakm** [comment]
@webinista Yes but could you make sure all the fonts are in Source Sans Pro?
