### ISSUE TITLE
Branding > Logo, Thread Image

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#127]
I do not have the descriptions of these yet because there might be a story i don't know about however when I do find out, I will go in and fill them in. Also, no code but buttons link to github

<img width="838" alt="screen shot 2016-03-04 at 5 31 08 pm" src="https://cloud.githubusercontent.com/assets/13420618/13544762/1439210c-e22f-11e5-956a-741d13e70c0f.png">

**View Logo** should go to: https://github.com/department-of-veterans-affairs/roadrunner/blob/master/assets/images/design/logo/logo.png

**View Thread Image** https://github.com/department-of-veterans-affairs/roadrunner/tree/master/assets/images/design/background

**Comment by webinista** [comment]
@gnakm we have two versions of the logo: one that's navy (pictured here) and one that's white. I'll link to them both. 

Also: The image is an AI file, which requires having Adobe Illustrator. Web teams might not have Illustrator, and shouldn't edit the file. This should probably link to a PNG or SVG file instead.

**Comment by gnakm** [comment]
Tiffany, could we actually have both versions up there and have them each link to the appropriate color? 

It would be nice to show the interaction of the white font on navy background because the VA turns yellow on hover. 
<img width="220" alt="screen shot 2016-03-07 at 3 21 55 pm" src="https://cloud.githubusercontent.com/assets/13420618/13582171/baa8ab20-e478-11e5-93d5-3d39bdc6e518.png">

We don't have to show interaction for the navy logo on white background because I think that logo will mostly be used for body copy (i.e. blog posts).

**Comment by webinista** [comment]
The hover effect is actually two different images ([hover image](https://www.vets.gov/assets/images/design/logo/logo-hover.png)). I think it makes sense to link to all three, but then we probably also need descriptions and usage guidelines for white vs hover.

**Comment by gnakm** [comment]
Maybe this description can encompass all of the logos: 

@emilyville Writing is not my forte but could you check to see if this makes sense? I'm still waiting (perhaps for Danny's return) to write a more in-depth description of the logo history. 

Alluding to our imageless brand, the vets.gov typographic logo is modern and easy to read in various sizes. For clear and crisp legibility, we chose white and primary darkest blue as our colors to evoke high contrast for all users. The white logo is mostly recognized on the header with a yellow hover that symbolizes the importance of the VA. The primary darkest blue logo is used mainly in body copies.

**Comment by emilyville** [comment]
Looks awesome @gnakm 

I made a few small edits (is "primary darkest" a thing that makes sense in this context? - if it's referenced elsewhere then we could add it back):

Alluding to our imageless brand, the vets.gov typographic logo is modern and easy to read in various sizes, and across devices. For clear and crisp legibility, we use white and blue as our colors to evoke high contrast for all users. The white logo is used in the header with a yellow hover, and the blue logo is used in body copy.
