### ISSUE TITLE
Navigation > Breadcrumb

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#128]
**Breadcrumb**
<img width="278" alt="screen shot 2016-03-07 at 10 09 44 am" src="https://cloud.githubusercontent.com/assets/13420618/13573258/c47f3c3a-e44c-11e5-9f56-b04dbf004142.png">
<img width="1423" alt="screen shot 2016-03-07 at 9 46 20 am" src="https://cloud.githubusercontent.com/assets/13420618/13573157/38b8bf00-e44c-11e5-9859-09e59e015b1b.png">

Description: 
Our breadcrumb appear in the header of each content page to help visitor navigate and keep track of their location. This clear and minimal pattern helps users steer through the navigational hierarchy without confusion and distractions from cluttered design.

**Comment by webinista** [comment]
Closing. We've redesigned breadcrumbs.
