### ISSUE TITLE
UI element: dropdown

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#13]
Need to specify:
- Hover states for results dropdown
- consistent interaction patterns
  -- hitting return
  -- inline submit options

Probably need to specify the js or jquery - I have a feeling GI Bill and VEC use different ones.

**Comment by gnakm** [comment]
@emilyville 
So currently there are two types of dropdowns:
This is across GI Bill and VEC
<img width="1045" alt="screen shot 2016-02-09 at 1 28 01 pm" src="https://cloud.githubusercontent.com/assets/13420618/12926748/d7ad03d4-cf32-11e5-9ce1-17cd95d4dba3.png">

These are type in text box drop downs. 
<img width="860" alt="screen shot 2016-02-09 at 1 32 41 pm" src="https://cloud.githubusercontent.com/assets/13420618/12926715/b52ece32-cf32-11e5-8a9b-b046f6e02c5a.png">

Everything is technically consistent right now except a minor issue we need to fix for resume builder but what do you think about making everything look like the latter? White with grey hover?

**Comment by emilyville** [comment]
When completed, make corresponding front end ticket

**Comment by gnakm** [comment]
From our last chat, we decided to stick to what we have as long as it's consistent.
We are going to use same one from 18F's style guide:
https://playbook.cio.gov/designstandards/form-controls/#dropdown

<img width="434" alt="screen shot 2016-02-17 at 3 56 04 pm" src="https://cloud.githubusercontent.com/assets/13420618/13124551/09470fea-d58f-11e5-943d-6ad453610f28.png">

<img width="373" alt="screen shot 2016-02-17 at 3 56 09 pm" src="https://cloud.githubusercontent.com/assets/13420618/13124555/0c78a5a2-d58f-11e5-8afa-9c2b4fec7466.png">

**Comment by webinista** [comment]
Can this issue be closed since the component already exists?
