### ISSUE TITLE
Add some padding in the footer on the mobiles

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#140]
Add some padding in the footer on the mobiles

![screen shot 2016-03-07 at 9 00 51 pm](https://cloud.githubusercontent.com/assets/1307774/13593359/6757c3e8-e4af-11e5-880e-cea90654783d.png)

This is not urgent or that huge of a deal, but adding anyway

**Comment by webinista** [comment]
This was an easy enough fix, so I added PR #143
