### ISSUE TITLE
Green buttons + logo images

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#141]
@gnakm The green buttons next to the logo image are a little jarring (just me?)

![screen shot 2016-03-07 at 9 23 36 pm](https://cloud.githubusercontent.com/assets/1307774/13593407/c6fea3ca-e4af-11e5-9a01-2e01832c0575.png)

**Comment by gnakm** [comment]
@emilyville It is not just you. Would it be weird to have one green button that says "View Logos" under all the three images that opens to the logo repo file instead of each specific file?

**Comment by webinista** [comment]
I think it would be a little weird, but we can link to the [repo directory](https://github.com/department-of-veterans-affairs/roadrunner/blob/master/assets/images/design/logo/) for all three images.

**Comment by emilyville** [comment]
closing because work is happening in vets-website
