### ISSUE TITLE
Thread image AI link

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#142]
Is there a reason to link to the illustrator file and not a normal png? If we want people to edit the file - that makes sense. Otherwise I think a png would make more sense (like the others) or both!

![screen shot 2016-03-07 at 9 24 36 pm](https://cloud.githubusercontent.com/assets/1307774/13593438/01dfc884-e4b0-11e5-8b52-b52a22baffc5.png)

**Comment by gnakm** [comment]
Good point. I just uploaded a [png version on github ](https://github.com/department-of-veterans-affairs/roadrunner/blob/master/assets/images/design/background/VA.Wave.png)

**Comment by gnakm** [comment]
I am going to close this because png file is up!
