### ISSUE TITLE
Resources & similar products to reference for Road Runner

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/roadrunner#19]
Hello team! I wanted to get an issue going where we could all add some resources for road runner. Feel free to add to this and include things that may inspire our work, exemplar style guides, or anything else that can help us figure out what we might want this to be like. 

To get us started....

**Content Resources** (also helpful in thinking about what this thing could look like)
- [Mail Chimp's voice and tone guide](http://voiceandtone.com/):  a great example of the type of thing we're trying to create, with lots of guidance about voice and tone.
- [Health Literacy Online](http://health.gov/healthliteracyonline/): A style guide Mary Ann worked on that takes people's literacy skills into account — with guidance about designing usable websites (even for people with very limited literacy skills)
- [18F content guide](https://pages.18f.gov/content-guide/)

**Design Resources**
- [US Web Design Standards](https://designschool.canva.com/blog/50-meticulous-style-guides-every-startup-see-launching/)
- [A cool list of excellent style guides from various brands](https://designschool.canva.com/blog/50-meticulous-style-guides-every-startup-see-launching/)

**Comment by emilyville** [comment]
Let's move this to a markdown file in this repo

**Comment by maryannbrody** [comment]
Closing this issue because I created a .md file in the roadrunner repo: https://github.com/department-of-veterans-affairs/roadrunner/blob/master/Resources.md
