### ISSUE TITLE
Create baseline Gemfile the project

### ISSUE THREAD

**Issue by jeffmaher** [department-of-veterans-affairs/roadrunner#2]
Defines the basic dependencies needed for a project. Things included should include:
- Basic JS libraries
- Style/CSS libraries
- Testing framework
- VA libraries commonly used (such as VA common)

**Comment by jeffmaher** [comment]
@shanear Mentioned looking at this:

https://github.com/thoughtbot/suspenders

**Comment by jeffmaher** [comment]
Also related to https://github.com/department-of-veterans-affairs/vets.gov-ops/issues/3 (versions for major libraries)

**Comment by jeffmaher** [comment]
Also related to https://github.com/department-of-veterans-affairs/vets.gov-ops/issues/24 (security scanner)

**Comment by emilyville** [comment]
@plusjeff and @shanear taking this one

**Comment by jeffmaher** [comment]
This has been divided into tasks in the roadrunner-rails repo, so closing this.
