### ISSUE TITLE
Set up different repositories

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#20]
we need different repositories and to combine the waffle boards.

This repository will be the one for the guide.
We'll keep tasks here for now.

**Comment by shanear** [comment]
@plusjeff alright, this one is up!

https://github.com/department-of-veterans-affairs/roadrunner-rails

**Comment by jeffmaher** [comment]
Created this for styles and associated Javascript

https://github.com/department-of-veterans-affairs/roadrunner-styles

**Comment by jeffmaher** [comment]
@emilyville Can you review the repos and the Jekyll PR? If those look good, this can get closed.
