### ISSUE TITLE
Choose linters

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/roadrunner#21]
I don't have much experience with ruby linters (because sometimes they annoy me), but on a larger team, they definitely have value. Especially if we end up hiring a small army of contractors. Do we include them in the roadrunner? thoughts?

Here are some potential linters (plus my hot take):

[ruby-lint](https://github.com/YorickPeterse/ruby-lint) - focuses on syntactic issues in ruby code (unused variables, etc). I strongly think we should use this.

[Rubocop](https://github.com/bbatsov/rubocop) - focuses on adherence to the somewhat ubiquitous [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide). Seems to be the go-to gem for doing this. I'd like to try this out, but my guess is that it'll be pretty finicky. Might require some configuration tweaking to be good.

[Reek](https://github.com/troessner/reek) - Focuses on more fuzzy stylistic ruby principles, which aren't necessarily based on an existing style guide, so it's not as well defined as Rubocop. Seems like it might be useful, but i'd pass on making it a blocking part of the workflow

**Comment by shanear** [comment]
My plan is to incorporate them in to caseflow-efolder-express and see what it's like to work with them, then report back.

**Comment by shanear** [comment]
@awong-dev @plusjeff @joesoftware love to hear ya'lls thoughts.

**Comment by awong-dev** [comment]
I've seen Rubocop used. I think we should start with that baseline.

I assume brakeman is a different category?

**Comment by awong-dev** [comment]
to be clear, I think we should use Rubocop ad ruby-lint in the baseline.

**Comment by shanear** [comment]
@awong-dev brakeman is focused on security vulnerabilities in rails specifically.

rubocop is general ruby coding style (each instead of for, # of lines in a method, 2 spaces not tabs, etc).

**Comment by shanear** [comment]
@awong-dev i'm going to open a separate issue for security related tools. These are all code style.

**Comment by awong-dev** [comment]
Yup. But ruby-lint being a static analysis tool kinda steps into security related bits too. Happy to have a separate discussion.

I say just take ruby-lint + rubocop and integrate it and close this issue. Then if there are problems, we can revisit.

Having style enforcement with a diverse set of devs is importent...  We'll be wanting to do the same for JS and CSS.  Heck, I might even be for moving to typescript in JS.

**Comment by shanear** [comment]
@awong-dev True, I forgot about adding those. I have a lot of experience with jshint, and love it, and think we should be using it.

For css, our friends at 18f, have one:
https://pages.18f.gov/frontend/css-coding-styleguide/
not sure what else is out there.

**Comment by awong-dev** [comment]
Yup. I think we should just use the 18F one cause...the world does not yet need another standard for styles. :)

eslint jshint jslint.... I have 0 experience, The language purist in me likes the eslint builds an AST, however it also looks younger and slower. As long as we can ensure everyone is using the same number of tabs, doesn't override Array.prototype, or do other silly things like leak bunches of unscoped variables into window, I'm happy.

**Comment by awong-dev** [comment]
Honestly though, for this, I would just legislate the tools. Put them in, and then people can send PRs later if they have complaints. Waiting for a N-way synchronization for quorum on stuff like this feels unnecessarily slow.

**Comment by shanear** [comment]
@awong-dev ok, after trying ruby-lint on our project, i'm realizing it does not play nicely with a lot of the rails loader magic (soooo.... many undeclared class errors)

after more research, it seems like rubocop alone is the standard.

FWIW, on our 9 file application, rubocop returned 60 offenses. Yikes.

**Comment by awong-dev** [comment]
That's 60 reasons to start using it now :)

**Comment by awong-dev** [comment]
(When I turned on htmlproof on vets.gov it had like 300 errors. that was a fun PR.)

**Comment by shanear** [comment]
Alright,

rubocop
scss-lint (with 18f's config)
jshint

are implemented in roadrunner-rails. Closing this one.
