### ISSUE TITLE
Add Side Navigation

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#25]
Each long set of information would be better served by a side nav (see USWDS for reference)

https://playbook.cio.gov/designstandards/sidenav/

Pros:
- This would help with our reliance on the piano keys.
- Something like the "disability benefits > Exposure to hazardous materials" section would be easier to navigate if you could more quickly switch between the (very small) sections of content. 
- we'll have less "pages"

Concerns:
- To keep sidenavs from taking over we should first decide what the right use case is for it and use sparingly
- how will it work on mobile?

**Comment by gnakm** [comment]
<img width="887" alt="screen shot 2016-02-25 at 6 32 03 pm" src="https://cloud.githubusercontent.com/assets/13420618/13338229/175ff848-dbee-11e5-9ee0-bfd88a3d8fea.png">
WIP - We talked about this in our vets.gov design meeting
Things to consider -- App view, scroll, when will this be used?

**Comment by webinista** [comment]
@emilyville @gnakm Can this issue be closed, or are we still iterating?

**Comment by gnakm** [comment]
@webinista We are still discussing this! Doesn't have to do with the side nav of RR.

**Comment by gnakm** [comment]
I think we can close this now!
