### ISSUE TITLE
Prototype using webpack / JS-specific packaging framework

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#30]
@shanear and @awong-dev 

pulled from issue #8 
And for context, decisions from meeting

​- Use USWDS styles
    - Not: grid, fonts
    - Use forms, colors

Use Neat for grid layout
Use 18F Styles Coding Guide
Work will be stored in several repos:
roadrunner-styles: Contains CSS/SCSS/JS
vets.gov-styles: Contains vets.gov specific CSS/SCSS/JS that compliment roadrunner-styles
General styles must be packaged for application stacks (Gems, NPM Modules, etc.)
roadrunner-styles will have package releases
Undecided: Gem, NPM Module (see actions)
ZIP for non-DS stacks: CSS/SCSS/JS uncompiled

**Comment by awong-dev** [comment]
Errr...is the subject right here?  using the style/convention decisions isn't the same as webpack / js-specific packaging framework. 

Also: https://github.com/department-of-veterans-affairs/roadrunner-rails/pull/30

or did you mean doing the above in a Jekyll friendly manner?

**Comment by emilyville** [comment]
yes! This is the issue for your PR #30. Not for Jekyll.

**Comment by emilyville** [comment]
I do not think this is relevant any longer. please reopen if needed.
