### ISSUE TITLE
Reassess linting configuration

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#34]

**Comment by awong-dev** [comment]
What's wrong with the linting configuration?

**Comment by shanear** [comment]
@awong-dev  The rubocop linting configuration is pretty aggressive. We've agreed to tone it down in our own project, not sure if we want to tone it down in road runner too.

see our config for the specifics:
https://github.com/department-of-veterans-affairs/caseflow-certification/blob/master/.rubocop.yml

**Comment by emilyville** [comment]
I do not think this is relevant any longer, please reopen if needed.
