### ISSUE TITLE
Side Navigation and Multiple Buttons on a Page

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#36]
@emilyville 
Bear with me.

This can be broken down into 2, possibly 3 issues but there is a reason why I put it together in one issue for now. After our VEC IA check in today, I was reminded that it is possible that there can potentially be multiple buttons on a page. 

Let's hypothetically say that we added these links on the GI Bill card  
<img width="710" alt="screen shot 2016-02-16 at 6 22 52 pm" src="https://cloud.githubusercontent.com/assets/13420618/13094734/b7b74c12-d4da-11e5-97a8-447e53b4561d.png">

...and that we decided to make them buttons (though I doubt Advanced Training and Certification would need a button because it's just a page). With our current style, it would probably look something like this:
**Mockup 1**
![2 buttons](https://cloud.githubusercontent.com/assets/13420618/13094845/65ccc958-d4db-11e5-84fb-9eb2d450e44f.png)

But then what happens if we were to have multiple buttons and a side nav for the long list of resources? I'm using 18F's side style. 
**Mockup 2**
![2 buttons on top with side nav](https://cloud.githubusercontent.com/assets/13420618/13094874/9e4f479c-d4db-11e5-86ec-9a4581d52b9f.png)

It started to get kind of busy and heavy on the right, which would be tough for scanning, so I mocked up this, which I am not too gungho about because I like that the breadcrumb aligns with the Title and description

**Mockup 3**
![left side nav](https://cloud.githubusercontent.com/assets/13420618/13094943/1555f94e-d4dc-11e5-9efe-219edbf952b0.png)

So then I tried something like this:
**Mockup 4**
![2 buttons with side nav](https://cloud.githubusercontent.com/assets/13420618/13094972/4c298e9a-d4dc-11e5-96df-2f393ed9676c.png)

Mobile version in general would more or less be the same as what we have now with the piano keys:

**Mockup 5**
![mobile portrait](https://cloud.githubusercontent.com/assets/13420618/13094986/7082903e-d4dc-11e5-863b-4635cf1dfc7d.png)

This whole issue may not be priority but I wanted to be prepared for the combinations of changes that may come ahead of us, esp with Careers & Employments happening and more talks about a side nav.

**Comment by emilyville** [comment]
ok this is a lot of things, you are right - but looks good!

for the two buttons: 
I'm trying to think of a scenario where we need two - and the best I can think of is the healthcare application where you can apply online, or download the form. I think that's a good enough one to say this is a thing we'll need. 

Defaulting to a primary and secondary - with the secondary styling as different. (thinking outlined style for the second would be a good place to start?)

![screen shot 2016-02-17 at 9 47 24 am](https://cloud.githubusercontent.com/assets/1307774/13118975/a1024a22-d55b-11e5-80bf-37705a20bfbf.png)

For the "Other Resources" panel, the issue I'm running into is - what if we also have a left nav for longer sections? We have a ton of flexibility with the piano keys as they are always being along the bottom so I am hesitant to change anything until we work those out. 

I totally can see a world where the piano keys turn into the right-hand panel on large screens, though, so maybe that's worth vetting. 

tagging mr @dannychapman for thoughts as well :)

**Comment by gnakm** [comment]
@emilyville Thanks for looking at this. Yeah secondary button works. Actually what if we just made that blue in grey outline button our "download" form button? That is if we won't run into any instances where there would be two buttons on one page. 

If we ever reach a world where piano keys turn into right-hang panels for desktops, we should do it for all...long list or short list. Because it can get confusing and don't want to ever give people the impression that it is for navigating.

**Comment by gnakm** [comment]
This issue has been broken down to 2 issues:
#72 Buttons and Sublinks
#73 Primary and Secondary Buttons
