### ISSUE TITLE
Add Piano Keys

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#43]
For right side / large screen

**Comment by gnakm** [comment]
![piano keys](https://cloud.githubusercontent.com/assets/13420618/13338201/e20a4194-dbed-11e5-80b8-7a6661a2dc83.png)
![piano keys hover](https://cloud.githubusercontent.com/assets/13420618/13338200/e209aec8-dbed-11e5-9a3e-adf7384bee15.png)

@emilyville Arrows!

**Comment by emilyville** [comment]
I like the arrow addition!

Tagging @dannychapman since it was his idea I think!

**Comment by dannychapman** [comment]
It was, and I like how this looks! Thanks @gnakm!

**Comment by dannychapman** [comment]
We might want to do this as an image and add to the icon sprite. Speaking of which, I have that as an illustrator file that we should add to both the vets.gov repo and this one...

**Comment by gnakm** [comment]
I am going to close this because we have new templates!
