### ISSUE TITLE
Do we need a engineering reference component to the jekyll site?

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#48]
I'm setting up collections (so far design, content, feedback) and wondering if we'll also want some documentation and reference for engineering specific information for set up etc., or will all of the information in the repository be sufficient for now?

I think it could have 
- getting started 
- coding syleguide (front end , maybe more)
- "how to work with us" meaning when we review things etc

**Comment by webinista** [comment]
We should definitely have a coding style guide (can be a CONTRIBUTING.md file) and a how-to-get set up guide. For the latter, README.md is probably enough.

**Comment by emilyville** [comment]
I do not think this issue is current, please reopen if necessary
