### ISSUE TITLE
Mockup for Jekyll site footer

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#50]

**Comment by gnakm** [comment]
![footer](https://cloud.githubusercontent.com/assets/13420618/13258868/ecdad3b2-da22-11e5-9af1-dc1ff04158df.png)

Toward a Veteran-Centered VA (PDF) - https://www.vets.gov/playbook/downloads/Toward_A_Veteran_Centered_VA.pdf

Voices of Veterans (PDF) - https://www.vets.gov/playbook/downloads/Voices_Of_Veterans.pdf

U.S. Digital Services Playbook - https://playbook.cio.gov/

U.S. Web Design Standards - https://playbook.cio.gov/designstandards/

Accessibility Guide - https://pages.18f.gov/accessibility/pagetitles/ 

Contribute to GitHub: https://github.com/department-of-veterans-affairs/roadrunner

**Comment by emilyville** [comment]
This looks awesome! 

You may want to add the links as you go to the issue - will make it much faster to build and sometimes there's discrepancy. I think github should probably go to the Jekyll rails, but I'm not sure.

**Comment by gnakm** [comment]
The way USWDS has it is it goes straight to their GH 18-F Standard page https://github.com/18F/web-design-standards . Maybe we can do that for ours for now?

**Comment by gnakm** [comment]
@webinista Sorry Tiffany! Could we change the background color to hex: 0F2D52
 So it looks like: 
<img width="854" alt="screen shot 2016-02-23 at 4 21 18 pm" src="https://cloud.githubusercontent.com/assets/13420618/13267113/8a97d142-da49-11e5-9078-d40a89e743cc.png">

**Comment by webinista** [comment]
@gnakm Yep. Can you could post the text for the "help us make it better" blurb here?

**Comment by gnakm** [comment]
@webinista 
Help us make it better!

Roadrunner was created by designers and developers of the Digital Services  at  the VA to standardize our projects, scale our teams and accelerate delivery. For any  feedback, please create an issue on our GitHub repository.

**Comment by webinista** [comment]
PR #56 contains these changes.
