### ISSUE TITLE
mockup for Jekyll site header

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#51]

**Comment by gnakm** [comment]
![top nav](https://cloud.githubusercontent.com/assets/13420618/13267200/17018cd6-da4a-11e5-8183-f311f637d8bd.png)

Getting Started
Design
Content
User Feedback

Header color: 032534
Active color: 133A4B
Font: Source Pro Sans Bold | 700 Weight; 24px
