### ISSUE TITLE
Mockup for Landing Page

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#55]
![landing page](https://cloud.githubusercontent.com/assets/13420618/13267461/588e2d8e-da4b-11e5-9a29-7dea0e17fb4c.png)

**Copy for Getting Started!** 

Roadrunner was designed to help the Digital Service team at the VA and Digital Service partners including VA employees and contractors build projects that will be migrated into Vets.gov and Appeals. The purpose of this open source style guide is to standardize our products, scale out team and accelerate our deliveries. When building a new app, team members can use the Roadrunner Github and help continue to build and upgrade the repository. 

View on Github url: https://github.com/department-of-veterans-affairs/roadrunner

**Building a single unified digital experience for all veterans.** 
Found on this page: 

The Challenge
1000+WEBSITES
9561-800 NUMBERS
42CALL CENTERS
220DATABASES
Today, the VA customer experience is fragmented, frustrating and confusing. Customers can’t find the information they need when they need it.

But their wants are simple. They desire:

Useful information that’s clearly written and presented, and;
Tools that are easy to find and use.
The new vets.gov intends to deliver both.

**Our Goals** https://www.vets.gov/playbook/
- Unifying and simplifying VA’s digital touch points, dramatically improving customer experience
- Meeting customer need on the first try, on any device
- Creating a mobile-first platform
- Retooling existing applications and designing new end-to-end experiences, in partnership with business owners across VA
- Providing transparency about our methods and processes

**Design Principles** https://www.vets.gov/playbook/
- Understand human need: design for people, rather than VA’s systems
- Assume every visitor is new
- Speak clearly, respectfully and directly
- Help people reach their goals every time
- Connect with customers. Create opportunities for feedback and dialog
- Research, observe, test and continuously improve
- Measure what matters
- Be device agnostic
- Employ modern development practices – be agile

**Comment by webinista** [comment]
@gnakm @emilyville Do these blocks link to anything? 
<img width="675" alt="screen shot 2016-02-24 at 1 17 20 pm" src="https://cloud.githubusercontent.com/assets/354277/13301264/f5efd98a-daf8-11e5-94f7-8d264e2f6469.png">
