### ISSUE TITLE
Deploy Road Runner

### ISSUE THREAD

**Issue by jeffmaher** [department-of-veterans-affairs/roadrunner#6]

**Comment by emilyville** [comment]
This only applies to the documentation, do something as light as possible (github pages + jekyll)

**Comment by jeffmaher** [comment]
Just realized this: By putting all the Jekyll files into the `src` folder, we dashed our hopes of being able to use GitHub pages super easily. 

@awong-dev @emilyville : Should I move them back to the root, and then make the default branch `gh-pages`? If not, we'll just have to make sure that when PRs get merged, we either deploy to vets.gov or to the gh-pages branch.

**Comment by jeffmaher** [comment]
Oh! I'm super wrong about this. It serves things up just fine. :smile: #jekyll-newb

**Comment by jeffmaher** [comment]
Made the gh-pages branch the default branch on Road Runner. Made it a protected branch.

**Comment by jeffmaher** [comment]
PR created for this. @emilyville for review.

**Comment by emilyville** [comment]
good! reviewed! Closing.
