### ISSUE TITLE
Buttons and Sublinks

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#72]
This has been an ongoing discussion but @dannychapman @KHarshawat @emilyville and I have narrowed it down to this design. 

![pasted_image_at_2016_02_22_06_50_pm](https://cloud.githubusercontent.com/assets/13420618/13305236/e0df3caa-db27-11e5-8859-92166c382268.png)

**Comment by dannychapman** [comment]
Crazy half-baked idea. What if we put the sublists back inside the blue button (don't hate me), but show then when you click / tap on the main category? They could expand down.

**Comment by dannychapman** [comment]
Styling could then be like the split button styling you had @gnakm.

**Comment by emilyville** [comment]
I like this @dannychapman!

**Comment by gnakm** [comment]
Memories! Closing because we are solving this issue with new templates!
