### ISSUE TITLE
Pick front end framework to start

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#8]
Could use the va_common soup
or straight gov web design standards
or foundation.

**Comment by jeffmaher** [comment]
Additionally, styling conventions are important (moving from #9 )

BEM / 18f / Medium

gather information, make decisions.

**Comment by emilyville** [comment]
Set up time to discsuss IRL (and over the phone) and to document decisions

**Comment by emilyville** [comment]
Everyone who attends should first try USWDS

**Comment by jeffmaher** [comment]
Meeting scheduled for Friday 2/5 to discuss and decide.

**Comment by jeffmaher** [comment]
Also, see #9 -- choosing Javascript frameworks (packaging, testing, SPA)

**Comment by plusjeff** [comment]
Outcome from Meeting

# Decisions
​
- Use USWDS styles
    - Not: grid, fonts
    - Use forms, colors
- Use Neat for grid layout
- Use 18F Styles Coding Guide
- Work will be stored in several repos:
    - roadrunner-styles: Contains CSS/SCSS/JS
    - vets.gov-styles: Contains vets.gov specific CSS/SCSS/JS that compliment roadrunner-styles
- General styles must be packaged for application stacks (Gems, NPM Modules, etc.)
    - roadrunner-styles will have package releases
    - Undecided: Gem, NPM Module (see actions)
    - ZIP for non-DS stacks: CSS/SCSS/JS uncompiled
​
# Actions
​
- Dependency Management (Shane, Albert)
    - Prototype using webpack / JS-specific packaging framework

**Comment by jeffmaher** [comment]
Decisions from meeting

​- Use USWDS styles
    - Not: grid, fonts
    - Use forms, colors
- Use Neat for grid layout
- Use 18F Styles Coding Guide
- Work will be stored in several repos:
  - roadrunner-styles: Contains CSS/SCSS/JS
  - vets.gov-styles: Contains vets.gov specific CSS/SCSS/JS that compliment roadrunner-styles
- General styles must be packaged for application stacks (Gems, NPM Modules, etc.)
  - roadrunner-styles will have package releases
  - Undecided: Gem, NPM Module (see actions)
  - ZIP for non-DS stacks: CSS/SCSS/JS uncompiled

**Comment by jeffmaher** [comment]
For next sprint Items:

​- Dependency Management (Shane, Albert)
    - Prototype using webpack / JS-specific packaging framework

**Comment by emilyville** [comment]
Created two new issues from this and closing this one!
