### ISSUE TITLE
What browsers do we support?

### ISSUE THREAD

**Issue by jeffmaher** [department-of-veterans-affairs/roadrunner#93]
Answer this and document it in the guide.

**Comment by webinista** [comment]
I think a good list is:
- Microsoft Edge (latest version)
- Internet Explorer 10 & 11
- Latest version of Chrome&dagger;
- Latest version of Firefox
- Safari / iOS Safari 8+ (current version is 9)
- iOS Safari 8+

What do current Vets.gov or VA.gov analytics look like in terms of browser usage?

---

&dagger; I'm including Chrome for Android in this, with a caveat. I think some recent Samsung Android devices  have both Samsung WebKit variant _and_ Chrome pre-installed)

**Comment by webinista** [comment]
Closing, since it's mostly a dup of #116
