### ISSUE TITLE
Side Navigation Color Detail

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#95]

**Comment by webinista** [comment]
Sort of related to #80

**Comment by gnakm** [comment]
<img width="97" alt="screen shot 2016-03-02 at 4 15 14 pm" src="https://cloud.githubusercontent.com/assets/13420618/13480351/1a7cc670-e092-11e5-854e-6bd230962f8e.png">

These are the specific details on the side nav.

Background #216380

Hover: #508EAA
Text Color: #FFFFFF
Active Font: Source Pro Sans Bold
Active Highlight:
Color of the section
 Branding  (pink)
#DB1271

Navigation
(yellow) #FDB81E

Page Elements
(Green) # 249A5B

Templates 
(Blue) # 20BCC4

Forms & Tools 
(red) # E64318
